fail_fast: true
repos:
  - repo: local
    hooks:
      - id: mix-format
        name: Format
        description: "Run 'mix format'."
        files: ^lib/
        entry: mix format
        language: system

      - id: mix-credo
        name: Credo
        description: "Run 'mix credo --strict'."
        files: ^lib/
        entry: mix credo --strict
        language: system

      - id: mix-dialyzer
        name: Dialyzer
        description: "Run 'mix dialyzer'."
        files: ^lib/
        entry: mix dialyzer
        language: system
