name: CI
on:
  push:
    branches: [1.x]
  pull_request:
    branches: [1.x]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.11.x]
        otp: [23.x]
    name: Check Code Quality
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          experimental-otp: true

      - name: Retrieve Build Cache
        uses: actions/cache@v1
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve PLT Cache
        uses: actions/cache@v1
        id: plt-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-v3-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      # something in 1.10.2 isn't formatted, but is in 1.10.4
      # - name: Check Formatting
      #   run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Run Coverage
        run: mix coveralls.json

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./cover/excoveralls.json

      - name: Run dialyzer
        run: |
          mkdir -p priv/plts
          mix dialyzer
